### ISSUE TITLE
Feature: Hide specific games from plugin list

### ISSUE THREAD

**Issue by TheStxfan** [KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher#28]
I would like an option to remove some of the installed games. as an example: I have portal and portal 2, but I already finished the first, so I would like to remove it from the list so that when I type gl only portal 2 appears.

**Comment by KrystianLesniak** [comment]
Hello. Thanks for contribution!

Yes, it will indeed be very useful, feature to hide certain games from plugin list is on my to-do feature list.

**Comment by TheStxfan** [comment]
> Hello. Thanks for contribution!
> 
> Yes, it will indeed be very useful, feature to hide certain games from plugin list is on my to-do feature list.

Thank you!

**Comment by KrystianLesniak** [comment]
This feature has been implemented in version 1.5.0: https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/releases/tag/v1.5.0
